package org.sohagroup.bsi.smsservice.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2021-12-27T11:34:07.215+03:30
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "BSaderatSendServiceSoap")
@XmlSeeAlso({ ObjectFactory.class })
public interface BSaderatSendServiceSoap {
    @WebMethod(operationName = "SendSMS_LikeToLike", action = "http://tempuri.org/SendSMS_LikeToLike")
    @RequestWrapper(localName = "SendSMS_LikeToLike", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendSMSLikeToLike")
    @ResponseWrapper(
        localName = "SendSMS_LikeToLikeResponse",
        targetNamespace = "http://tempuri.org/",
        className = "org.tempuri.SendSMSLikeToLikeResponse"
    )
    public void sendSMSLikeToLike(
        @WebParam(name = "Message", targetNamespace = "http://tempuri.org/") ArrayOfString message,
        @WebParam(name = "DestinationAddress", targetNamespace = "http://tempuri.org/") ArrayOfString destinationAddress,
        @WebParam(name = "Number", targetNamespace = "http://tempuri.org/") String number,
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/") String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/") String password,
        @WebParam(name = "IP_Send", targetNamespace = "http://tempuri.org/") String ipSend,
        @WebParam(name = "Company", targetNamespace = "http://tempuri.org/") String company,
        @WebParam(
            mode = WebParam.Mode.INOUT,
            name = "SendStatus",
            targetNamespace = "http://tempuri.org/"
        ) javax.xml.ws.Holder<String> sendStatus,
        @WebParam(
            mode = WebParam.Mode.INOUT,
            name = "BatchID",
            targetNamespace = "http://tempuri.org/"
        ) javax.xml.ws.Holder<String> batchID,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Amount", targetNamespace = "http://tempuri.org/") javax.xml.ws.Holder<String> amount,
        @WebParam(
            mode = WebParam.Mode.INOUT,
            name = "chargingAmount",
            targetNamespace = "http://tempuri.org/"
        ) javax.xml.ws.Holder<String> chargingAmount,
        @WebParam(
            mode = WebParam.Mode.OUT,
            name = "SendSMS_LikeToLikeResult",
            targetNamespace = "http://tempuri.org/"
        ) javax.xml.ws.Holder<ArrayOfSTCSMSSend> sendSMSLikeToLikeResult
    );

    @WebMethod(operationName = "StatusSMS", action = "http://tempuri.org/StatusSMS")
    @RequestWrapper(localName = "StatusSMS", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StatusSMS")
    @ResponseWrapper(localName = "StatusSMSResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StatusSMSResponse")
    @WebResult(name = "StatusSMSResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfSTCSMSStatus statusSMS(
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/") String userName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/") String password,
        @WebParam(name = "IP_Send", targetNamespace = "http://tempuri.org/") String ipSend,
        @WebParam(name = "Company", targetNamespace = "http://tempuri.org/") String company,
        @WebParam(name = "BatchId", targetNamespace = "http://tempuri.org/") String batchId
    );

    @WebMethod(operationName = "GetRemainCredit", action = "http://tempuri.org/GetRemainCredit")
    @RequestWrapper(localName = "GetRemainCredit", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRemainCredit")
    @ResponseWrapper(
        localName = "GetRemainCreditResponse",
        targetNamespace = "http://tempuri.org/",
        className = "org.tempuri.GetRemainCreditResponse"
    )
    @WebResult(name = "GetRemainCreditResult", targetNamespace = "http://tempuri.org/")
    public String getRemainCredit(
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/") String userName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/") String password,
        @WebParam(name = "Company", targetNamespace = "http://tempuri.org/") String company,
        @WebParam(name = "IP_Send", targetNamespace = "http://tempuri.org/") String ipSend
    );

    @WebMethod(operationName = "SendSMS_Single", action = "http://tempuri.org/SendSMS_Single")
    @RequestWrapper(localName = "SendSMS_Single", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendSMSSingle")
    @ResponseWrapper(
        localName = "SendSMS_SingleResponse",
        targetNamespace = "http://tempuri.org/",
        className = "org.tempuri.SendSMSSingleResponse"
    )
    @WebResult(name = "SendSMS_SingleResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfString sendSMSSingle(
        @WebParam(name = "Message", targetNamespace = "http://tempuri.org/") String message,
        @WebParam(name = "DestinationAddress", targetNamespace = "http://tempuri.org/") String destinationAddress,
        @WebParam(name = "Number", targetNamespace = "http://tempuri.org/") String number,
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/") String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/") String password,
        @WebParam(name = "IP_Send", targetNamespace = "http://tempuri.org/") String ipSend,
        @WebParam(name = "Company", targetNamespace = "http://tempuri.org/") String company,
        @WebParam(name = "IsFlash", targetNamespace = "http://tempuri.org/") boolean isFlash
    );

    @WebMethod(operationName = "SendSMS_Batch", action = "http://tempuri.org/SendSMS_Batch")
    @RequestWrapper(localName = "SendSMS_Batch", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendSMSBatch")
    @ResponseWrapper(
        localName = "SendSMS_BatchResponse",
        targetNamespace = "http://tempuri.org/",
        className = "org.tempuri.SendSMSBatchResponse"
    )
    @WebResult(name = "SendSMS_BatchResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfString sendSMSBatch(
        @WebParam(name = "Message", targetNamespace = "http://tempuri.org/") String message,
        @WebParam(name = "DestinationAddress", targetNamespace = "http://tempuri.org/") ArrayOfString destinationAddress,
        @WebParam(name = "Number", targetNamespace = "http://tempuri.org/") String number,
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/") String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/") String password,
        @WebParam(name = "IP_Send", targetNamespace = "http://tempuri.org/") String ipSend,
        @WebParam(name = "Company", targetNamespace = "http://tempuri.org/") String company,
        @WebParam(name = "IsFlash", targetNamespace = "http://tempuri.org/") boolean isFlash
    );

    @WebMethod(operationName = "SendSMS_Batch_Full", action = "http://tempuri.org/SendSMS_Batch_Full")
    @RequestWrapper(localName = "SendSMS_Batch_Full", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendSMSBatchFull")
    @ResponseWrapper(
        localName = "SendSMS_Batch_FullResponse",
        targetNamespace = "http://tempuri.org/",
        className = "org.tempuri.SendSMSBatchFullResponse"
    )
    public void sendSMSBatchFull(
        @WebParam(name = "Message", targetNamespace = "http://tempuri.org/") String message,
        @WebParam(name = "DestinationAddress", targetNamespace = "http://tempuri.org/") ArrayOfString destinationAddress,
        @WebParam(name = "Number", targetNamespace = "http://tempuri.org/") String number,
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/") String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/") String password,
        @WebParam(name = "IP_Send", targetNamespace = "http://tempuri.org/") String ipSend,
        @WebParam(name = "Company", targetNamespace = "http://tempuri.org/") String company,
        @WebParam(name = "IsFlash", targetNamespace = "http://tempuri.org/") boolean isFlash,
        @WebParam(
            mode = WebParam.Mode.INOUT,
            name = "SendStatus",
            targetNamespace = "http://tempuri.org/"
        ) javax.xml.ws.Holder<String> sendStatus,
        @WebParam(
            mode = WebParam.Mode.INOUT,
            name = "BatchID",
            targetNamespace = "http://tempuri.org/"
        ) javax.xml.ws.Holder<String> batchID,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Amount", targetNamespace = "http://tempuri.org/") javax.xml.ws.Holder<String> amount,
        @WebParam(
            mode = WebParam.Mode.INOUT,
            name = "chargingAmount",
            targetNamespace = "http://tempuri.org/"
        ) javax.xml.ws.Holder<String> chargingAmount,
        @WebParam(
            mode = WebParam.Mode.OUT,
            name = "SendSMS_Batch_FullResult",
            targetNamespace = "http://tempuri.org/"
        ) javax.xml.ws.Holder<ArrayOfSTCSMSSend> sendSMSBatchFullResult
    );
}
