package org.sohagroup.bsi.smsservice.tempuri;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2021-12-27T11:34:07.258+03:30
 * Generated source version: 3.5.0
 *
 */
@WebServiceClient(
    name = "BSaderatSendService",
    wsdlLocation = "file:/home/bahram/IdeaProjects/sms_saderat/src/main/resources/smssaderat.wsdl",
    targetNamespace = "http://tempuri.org/"
)
public class BSaderatSendService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://tempuri.org/", "BSaderatSendService");
    public static final QName BSaderatSendServiceSoap = new QName("http://tempuri.org/", "BSaderatSendServiceSoap");
    public static final QName BSaderatSendServiceSoap12 = new QName("http://tempuri.org/", "BSaderatSendServiceSoap12");

    static {
        URL url = null;
        try {
            url = new URL("file:/home/bahram/IdeaProjects/sms_saderat/src/main/resources/smssaderat.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger
                .getLogger(BSaderatSendService.class.getName())
                .log(
                    java.util.logging.Level.INFO,
                    "Can not initialize the default wsdl from {0}",
                    "file:/home/bahram/IdeaProjects/sms_saderat/src/main/resources/smssaderat.wsdl"
                );
        }
        WSDL_LOCATION = url;
    }

    public BSaderatSendService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BSaderatSendService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BSaderatSendService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BSaderatSendService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BSaderatSendService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BSaderatSendService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BSaderatSendServiceSoap
     */
    @WebEndpoint(name = "BSaderatSendServiceSoap")
    public BSaderatSendServiceSoap getBSaderatSendServiceSoap() {
        return super.getPort(BSaderatSendServiceSoap, BSaderatSendServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BSaderatSendServiceSoap
     */
    @WebEndpoint(name = "BSaderatSendServiceSoap")
    public BSaderatSendServiceSoap getBSaderatSendServiceSoap(WebServiceFeature... features) {
        return super.getPort(BSaderatSendServiceSoap, BSaderatSendServiceSoap.class, features);
    }

    /**
     *
     * @return
     *     returns BSaderatSendServiceSoap
     */
    @WebEndpoint(name = "BSaderatSendServiceSoap12")
    public BSaderatSendServiceSoap getBSaderatSendServiceSoap12() {
        return super.getPort(BSaderatSendServiceSoap12, BSaderatSendServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BSaderatSendServiceSoap
     */
    @WebEndpoint(name = "BSaderatSendServiceSoap12")
    public BSaderatSendServiceSoap getBSaderatSendServiceSoap12(WebServiceFeature... features) {
        return super.getPort(BSaderatSendServiceSoap12, BSaderatSendServiceSoap.class, features);
    }
}
